version: "3.8"
services:
  mysql:
    container_name: quiz_museu_soares_reis_mysql
    image: mysql:latest
    restart: unless_stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: projeto_jt
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    container_name: quiz_museu_soares_reis_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: unless_stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  node_app:
  mysql_data: